# Generated by Django 3.1.2 on 2021-06-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
